version: "3"

services:
  app:
    container_name: gousto_api_test
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    networks:
      - app-tier
    ports:
      - 80:80
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app

  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    networks:
      - app-tier

volumes:
  redisdata:
    driver: "local"

networks:
  app-tier:
    driver: bridge